domain_root_path: ./data/input
output_dir_path: ./data/output
commit_message: "Auto-sync from demo"

s3_config:
  bucket_name: "yantra-data"
  endpoint_url: "http://localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  region: "us-east-1"
  use_ssl: false

mlflow_config:
  tracking_uri: "http://localhost:5000"
  experiment_name: "Yantra_Demo_Runs"

gemini_config:
  model_name: "gemini-1.5-flash"
  temperature: 0.7